"""Configuration des noms des rues"""

TYPE_VOIES = [
    "Rue"
]

KEYWORDS = [
    "Léopold Sédar Senghor",
    "Cheikh Anta Diop",
    "Mamadou Dia",
    "Blaise Diagne",
    "Lat Dior Ngoné Latyr Diop",
    "Alboury Ndiaye",
    "Maba Diakhou Bâ",
    "Aline Sitoé Diatta",
    "Soundiata Keïta",
    "Ahmadou Bamba",
    "El Hadj Malick Sy",
    "Serigne Fallou Mbacké",
    "Serigne Babacar Sy",
    "Seydina Limamou Laye",
    "Ousmane Dan Fodio",
    "Ousmane Sembène",
    "Birago Diop",
    "Aminata Sow Fall",
    "Cheikh Hamidou Kane",
    "Yandé Codou Sène",
    "Ndiadiane Ndiaye",
    "Kocc Barma Fall",
    "Boubacar Joseph Ndiaye",
    "Samory Touré",
    "Mohamed VI",
    "de la Teranga",
    "de la Souveraineté",
    "de l'Unité Africaine",
    "de la Paix",
    "de la Liberté",
    "de la Baobab",
    "de Djoudj",
    "Niokolo Koba",
    "Sine Saloum",
    "Casamance",
    "du Bissap",
    "des Pêcheurs",
    "des Tisserands",
    "des Forgerons",
    "des Marchés",
    "Kwame Nkrumah",
    "Thomas Sankara",
    "Nelson Mandela",
    "Patrice Lumumba",
    "Haïlé Sélassié",
    "de la Renaissance",
    "de l'Espoir",
    "de la Fraternité",
    "de l'Égalité",
    "de la Résilience",
    "Jigeen",
    "Mariama Ba",
    "Ken Bougoul",
]

